defaults:
  - _self_
  - datasets_info: Tmall
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe

temp: 1
type_loss: entmax #entmax
counts: False

adj: 

hydra:
  sweeper:
    direction: maximize
    study_name: ${datasets_info.name}
    storage: 'sqlite:///GRU4Rec-${datasets_info.name}-${type_loss}.db'
    n_trials: 50
    n_jobs: 1
    params:
      model_params.input_size: range(64, 256, step=32)
      model_params.num_layers: choice(1, 2, 4)
      model_params.dropout: range(0.1, 0.5, 0.1)
      temp: tag(log, interval(0.1, 100))

random_state: 17
cuda_visible_devices: 2

optimization_metric: NDCG@10

dataset_params:
  max_length: 64
  num_negatives: 

dataloader:
  batch_size: 64
  test_batch_size: 64
  num_workers: 8
 
model: GRU4Rec
model_params:
  input_size: 64
  hidden_size: ${model_params.input_size}
  num_layers: 1
  dropout: 0.1
  
seqrec_module:
  lr: 0.001
  predict_top_k: 10  # this value is used for validation
  filter_seen: False

trainer_params:
  max_epochs: 100
patience: 10
top_k_metrics: [10, 100]

project_name: entmax/GRU4Rec/hyper/${datasets_info.name}_${type_loss}
task_name: 'experiments'